### ISSUE TITLE
Possible cause of crash at 18xx.games tile page.

### ISSUE THREAD

**Issue by gchambers419** [18xx-maker/games#14]
https://github.com/18xx-maker/games/blob/206c7c3ceb0f3dc0d16a5b03b7bbae566dfc1638/games/1817.json#L318

The empty market array is being rendered in a way that's crashing the code that loads the game.

The "real" market is 2-D, with some unusual left-most locations:

- A space labeled "Liquidation"
- Three spaces labeled "Acquisition"
- Normal prices as follows: 40 - 70 by 5's, 80 - 120 by 10's, 135 - 200 by 15's
- 220, 245, 270, 300, 330, 360, 400, 440, 490, 540, 600

**Comment by kelsin** [comment]
Agreed, since 1817 isn't the priority on 18xx.games it hasn't gotten attention to finish the game file in this repo. PR's accepted for anyone that wants to flesh out 1817. Otherwise we'll get to it later.

**Comment by gchambers419** [comment]
Understood, if it weren't for the weird lower positions, I might have tossed in a PR despite not being able to test yet.

Does the maker app have any concept of "slots" below the actual market values?  I skimmed the 1817 rules but didn't look for the impact on a player's net worth of companies whose stock is in "acquisition."

**Comment by kelsin** [comment]
Acquisition counts as 40 value for stock value and other purposes (double jumps etc). Yeah 18xx-maker it's just putting labels in. However behavior in 18xx.games will require other stuff and the syntax is probably not known yet :)
